; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32@6.6.0
framework = arduino

monitor_speed = 115200
lib_deps = bodmer/TFT_eSPI@^2.5.33

[env:fri3d2024]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
	-D BINF_PLATFORM=FRI3D2024
    -D BOARD_HAS_PSRAM           ; N16R8V has PSRAM
    -D ARDUINO_USB_MODE=1        ; necessary for serial port
    -D ARDUINO_USB_CDC_ON_BOOT=1 ; necessary for serial port
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
 	-D USE_HSPI_PORT
	-D TFT_RGB_ORDER=TFT_BGR 	; swap red and blue byte order
	-D TFT_INVERSION_OFF
	-D TFT_WIDTH=296  			; init the eSPI lib with correct dimensions
	-D TFT_HEIGHT=240 			; init the eSPI lib with correct dimensions
	-D TFT_MISO=8
	-D TFT_MOSI=6
	-D TFT_SCLK=7
	-D TFT_CS=5
	-D TFT_DC=4
	-D TFT_RST=48
	-D LOAD_GLCD=1
	-D SPI_FREQUENCY=80000000

[env:fri3d2026]
board = 4d_systems_esp32s3_gen4_r8n16
board_upload.flash_size = 16MB
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI
build_flags = 
	-D BINF_PLATFORM=FRI3D2026
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D USER_SETUP_LOADED
	-D USE_HSPI_PORT
	-D ST7789_DRIVER
	-D TFT_RGB_ORDER=TFT_BGR
	-D TFT_INVERSION_ON
	-D TFT_MISO=8
	-D TFT_MOSI=6
	-D TFT_SCLK=7
	-D TFT_CS=5
	-D TFT_DC=4
	-D TFT_RST=11
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=240
	-D LOAD_GLCD=1
	-D SPI_FREQUENCY=80000000